[project]
name = "fastapi-i18n"
version = "0.3.0"
authors = [{name="HeiGIT ohsome team", email="ohsome@heigit.org"}]
description = "FastAPI Internationalization (i18n)"
readme = "README.md"
requires-python = ">=3.10,<3.14"

classifiers = [
    "Framework :: FastAPI",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
license = "LGPL-3.0-only"
license-files = ["COPYING*"]
dependencies = [
    "fastapi>=0.109.2",
    "httpx>=0.23.0",
]

[project.urls]
Homepage = "https://ohsome.org/"
# TODO: update once dedicated documentation is available
Documentation = "https://github.com/GIScience/fastapi-i18n/blob/main/README.md"
Repository = "https://github.com/GIScience/fastapi-i18n"
Issues = "https://github.com/GIScience/fastapi-i18n/issues"
# TODO: create changelog
# Changelog = "https://github.com/GIScience/fastapi-i18n/blob/main/CHANGELOG.md"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=7.0.0",
    "ruff==0.14.1",
]

[tool.uv.build-backend]
module-root = ""  # use fastapi-i18n/ as root instead the default src/fastapi-i18n

[tool.ruff.lint]
select = [
    "E",    # pycodestyle Error
    "F",    # Pyflakes
    "I",    # isort
    "N",    # pep8-nameing
    "Q",    # flake8-quotes
    "W",    # pycodestyle Warning
    "C90",  # mccabe
    "TRY",  # tryceratops
    "RUF",  # ruff-specific rules
    "FURB", # refurb
    "PERF", # perflint
    "S",    # bandit
    "B",    # bugbear
    "SIM",  # simplify
]

[tool.ruff.lint.extend-per-file-ignores]
"tests/*" = ["S101"]  # S101 usage of asserts
